



FEATURE_MAPPING = {
    'ID': 'ID',
    'Crossing': 'Crossing',
    'Finishing': 'Finishing',
    'Heading accuracy': 'HeadingAccuracy',
    'Short passing': 'ShortPassing',
    'Volleys': 'Volleys',
    'Dribbling': 'Dribbling',
    'Curve': 'Curve',
    'FK Accuracy': 'FKAccuracy',
    'Long passing': 'LongPassing',
    'Ball control': 'BallControl',
    'Acceleration': 'Acceleration',
    'Sprint speed': 'SprintSpeed',
    'Agility': 'Agility',
    'Reactions': 'Reactions',
    'Balance': 'Balance',
    'Shot power': 'ShotPower',
    'Jumping': 'Jumping',
    'Stamina': 'Stamina',
    'Strength': 'Strength',
    'Long shots': 'LongShots',
    'Aggression': 'Aggression',
    'Interceptions': 'Interceptions',
    'Positioning': 'Positioning',
    'Vision': 'Vision',
    'Penalties': 'Penalties',
    'Marking': 'Marking',
    'Standing tackle': 'StandingTackle',
    'Sliding tackle': 'SlidingTackle',
    'GK Diving': 'GKDiving',
    'GK Handling': 'GKHandling',
    'GK Kicking': 'GKKicking',
    'GK Positioning': 'GKPositioning',
    'GK Reflexes': 'GKReflexes',
    'Best Position': 'Best Position',
    'Best Overall Rating': 'Best Overall Rating',
    'Release Clause': 'Release Clause',
    'DefensiveAwareness': 'DefensiveAwareness'
}